CREATE TABLE IF NOT EXISTS user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    memberId INTEGER NOT NULL DEFAULT 0,
    guildId INTEGER NOT NULL DEFAULT 0,
    deleted TEXT NOT NULL DEFAULT 'no',
    created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS strike (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    userId INTEGER NOT NULL DEFAULT 0,
    messageId NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'pending',
    honored TEXT NOT NULL DEFAULT '0000-00-00',
    created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES user(id)
);
